config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  resources :questions
  devise_for :users
  get 'questions/index'
  post 'answers/create'
  post 'comments/create'
  post 'questions/:question_id/:user_id', to: 'questions#vote_up', as: 'vote_up'
  post 'answers/:answer_id/:user_id', to: 'answers#ans_vote_up', as: 'ans_vote_up'

end

app/models/answer.rb
class Answer < ApplicationRecord
    acts_as_voteable
    belongs_to :question
    has_many :comments, as: :commentable
    validates :description, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/question.rb
class Question < ApplicationRecord
    acts_as_voteable
    validates :title, :body, presence: true
    belongs_to :user
    has_many  :comments, as: :commentable
    has_many :answers
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions
  has_many :answers, through: :users
  acts_as_voter
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  scope :for_voter, lambda { |*args| where(["voter_id = ? AND voter_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :for_voteable, lambda { |*args| where(["voteable_id = ? AND voteable_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :recent, lambda { |*args| where(["created_at > ?", (args.first || 2.weeks.ago)]) }
  scope :descending, lambda { order("created_at DESC") }

  belongs_to :voteable, :polymorphic => true
  belongs_to :voter, :polymorphic => true

  attr_accessible :vote, :voter, :voteable if ActiveRecord::VERSION::MAJOR < 4


  # Comment out the line below to allow multiple votes per user.
  validates_uniqueness_of :voteable_id, :scope => [:voteable_type, :voter_type, :voter_id]

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  skip_before_action :verify_authenticity_token

  def new; end

  def create
    user = current_user
    @question = Question.find(params[:question_id])
    @answer = @question.answers.create(answer_params)

    if @answer.save
      redirect_to question_path(params[:question_id]), notice: 'Respuesta añadida correctamente.'
    else
      redirect_to question_path(params[:question_id]), alert: 'La respuesta no debe estar vacia.'
    end
    end

  def ans_vote_up
    user = User.find(params[:user_id])
    @answer = Answer.find(params[:answer_id])
    @question_id=Answer.find(params[:answer_id]).question.id

    if !user.voted_on?(@answer)
      user.vote_exclusively_for(@answer)
      redirect_to question_path(@question_id)
    else
      user.unvote_for(@answer)
      redirect_to question_path(@question_id)
    end
  end

  private

  def answer_params
    params.permit(:description, :answer_id, :user_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  protect_from_forgery with: :null_session

  def create
    if params[:type]=='Question'
      @res = Question.find(params[:id])
    else
      @res = Answer.find(params[:id])
    end

    Comment.create(commentable: @res, text: params[:comment])
    redirect_to question_path(params[:val_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :id, :type, :val_id)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  protect_from_forgery with: :null_session

  def index
    if params[:terms].present?
      @questions = Question.where('title LIKE (?) OR body LIKE (?)', "%#{params[:terms]}%", "%#{params[:terms]}%")
    else
      @questions = Question.all.order(created_at: :desc)
    end
  end

  def show
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
    @question = Question.find(params[:id])
    @answer = Answer.all.where(question_id: params[:id])
  end

  def new
    user = current_user
    @question = user.questions.new
  end

  def create
    user = current_user
    @question = user.questions.new(question_params)

    if @question.save
      redirect_to questions_path, notice: 'Pregunta añadida correctamente.'
    else
      redirect_to new_question_path, alert: 'No se pudo crear la pregunta, debe ingresar título y descripción.'
    end
  end

  def edit; end

  def update; end

  def destroy; end

  def vote_up
    user = User.find(params[:user_id])
    @question = Question.find(params[:question_id])

    if !user.voted_on?(@question)
      user.vote_exclusively_for(@question)
      redirect_to question_path(params[:question_id])
    else
      user.unvote_for(@question)
      redirect_to question_path(params[:question_id])
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, :user_id, :question_id)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid col-md-10 col-md-offset-1">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
        aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Flow<strong>Overstack</strong></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse " id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="active">

          <% if user_signed_in? %>
          <li><a href=""><%= current_user.email %></a></li>
          <li><%= link_to 'Salir', destroy_user_session_path, method: 'DELETE'%></li>
          <% else %>
          <li><%= link_to 'Regístrate', new_user_registration_path, method: 'GET'%></li>
          <li><%= link_to 'Ingresa', new_user_session_path, method: 'GET'%></li>
          <%end%>
          <li><%= form_tag questions_index_path, class:'navbar-form navbar-left', method: :get do %>
            <div class="form-group">
              <%= text_field_tag :terms, params[:terms], class: "form-control", placeholder: "Buscar..." %>
            </div>
            <%= submit_tag 'Buscar', name: nil, class: "btn btn-default btn-md" %>
            <% end %>
            
          </li>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Flowoverstack</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>
<body>
  <%= render 'layouts/header' %>

    <% if notice %>
      <div class="col-md-6 col-md-offset-3 alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <% if alert %>
      <div class=" col-md-6 col-md-offset-3 alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= alert %>
      </div>
    <% end %>

    <%=yield %>

    <nav class="navbar-wrapper navbar-inverse navbar-fixed-bottom">
      <div class="container-fluid">
        <p class="navbar-text">&copy; 2018, by: 56Kz</p>
        <a href="https://github.com/56kz" class="btn navbar-btn btn-default" target="_blank">GitHub</a>
      </div>
    </nav>

</body>
</html>

app/views/questions/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <h1>Preguntas</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-10 col-md-offset-1 text-right">
      <%= link_to '<strong>Hacer una pregunta</strong>'.html_safe, new_question_path, class:'btn btn-primary' %>
    </div>
  </div><br>

  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <table class="table">
        <tbody>
          <% @questions.each do |question| %>
          <tr>
            <td class="text-center">
              <h4><%= question.votes.count %></h4>
              <p>Votos</p>
            </td>
            <td class="text-center">
              <h4><%= question.answers.count %></h4>
              <p>Respuestas</p>
            </td>
            <td class="text-left link-center">
              <h4><%= link_to question.title, question, class:'custom-color'%></h4>
              <p><%= question.user.email %> preguntó hace <% elapsed=Time.now.to_time-question.created_at.to_time%>
                <% if (elapsed.to_i/(60*60*24)) >30 %>
                <%= (elapsed.to_i/(60*60*24))/30 %> meses
                <% elsif (elapsed.to_i/(60*60*24)) <1 %>
                <%= (elapsed.to_i/(60*60)) %> horas
                <% else %>
                <%= (elapsed.to_i/(60*60*24)) %> dias
                <% end %>
              </p>
            </td>
            <td></td>
          </tr>
            <% end %>
        </tbody>
      </table><br>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="container-fluid">
  <div class="row justify-content-md-center">
    <div class="col-md-6 col-md-offset-3">
      <h1> Publicar Pregunta </h1>
      <%= form_for @question do |f| %>
      <div class="form-group">
        <%= f.text_field :title, class:"form-control", id:"title_text", placeholder:'Título'%>
      </div>
      <div class="form-group">
        <%= f.text_area :body, class:"form-control", id:"body_text", placeholder:'Descripción', rows:'5'%>
      </div>
      <div class="form-group">
        <strong><%= f.submit '¡Preguntar!', class:"btn btn-primary btn-block"%></strong>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<div class="container-fluid">
  <div class="row justify-content-md-center">
    <div class="col-md-8 col-md-offset-2">
      <h1><%= @question.title %></h1>
      <div class="row justify-content-md-right">
        <div class="col-md-1 text-center">
          <div>
            <% if user_signed_in? %>
            <%= link_to '<span class="glyphicon glyphicon-triangle-top"></span>'.html_safe, vote_up_path(@question.id, current_user.id), method: 'POST'%>
            <% else %>
              <span class="glyphicon glyphicon-triangle-top"></span>
            <% end %>
          </div>
          <p><%= @question.votes.count %></p>
        </div>
      </div>
      <div class="col-md-11">
        <p><%= @markdown.render(@question.body).html_safe %></p>
        <div class="row"><hr></hr>
          <% @question.comments.each do |c| %>
          <p><%= c.text %></p><hr></hr>
          <% end %>

          <% if user_signed_in? %>
            <form form action="/comments/create" method="post">
              <div class="form-group">
                <input type="hidden" name="id" value=<%= @question.id %>>
                <input type="hidden" name="type" value=<%= "Question" %>>
                <input type="hidden" name="val_id" value=<%=  @question.id  %>>
                <textarea name="comment" name="text" class="form-control" rows="2" placeholder="Agrega un comentario."></textarea><br>
                <div class="text-right">
                  <button type="submit" class="btn btn-primary">Comentar</button>
                </div>
              </div>
            </form>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row justify-content-md-right">
  <div class="col-md-8 col-md-offset-2">
    <h3><%= @answer.count %> Respuesta(s)</h3><hr></hr>
    <div class="row justify-content-md-right">
      <%@answer.each do |ans|%>
      <div class="col-md-1 text-center">
        <div class="answer">
          <div class"answertwo">
            <% if user_signed_in? %>
            <%= link_to '<span class="glyphicon glyphicon-triangle-top"></span>'.html_safe, ans_vote_up_path(ans.id, current_user.id), method: 'POST'%>
            <% else %>
            <span class="glyphicon glyphicon-triangle-top"></span>
            <% end %>
          </div>
          <p> <%= ans.votes.count %> </p>
        </div>
      </div>
      <div class="col-md-11">
        <p><%= @markdown.render(ans.description).html_safe %></p>
        <div class="row"><hr></hr>
          <% ans.comments.each do |c| %>
          <p><%= c.text %></p><hr></hr>
          <% end %>

          <% if user_signed_in? %>
          <form form action="/comments/create" method="post">
            <div class="form-group">
              <input type="hidden" name="id" value=<%= ans.id %>>
              <input type="hidden" name="type" value=<%= "Answer" %>>
              <input type="hidden" name="val_id" value=<%=  @question.id  %>>
              <textarea name="comment" name="text" class="form-control" rows="2" placeholder="Agrega un comentario."></textarea><br>
              <div class="text-right">
                <button type="submit" class="btn btn-primary">Comentar</button>
              </div>
            </div>
          </form>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col-md-12">
        <h3>Tu Respuesta</h3>
        <% if user_signed_in? %>
        <form form action="/answers/create" method="post">
          <div class="form-group">
            <input type="hidden" name="question_id" value=<%= @question.id %>>
            <textarea name="description" class="form-control" rows="5" placeholder="Agrega una respuesta."></textarea><br>
            <div class="text-right">
              <button type="submit" class="btn btn-primary">Responder</button>
            </div><br><br><br><br>
          </div>
        </form>
        <%else%>
        <div class="well">Debes ingresar para responder una pregunta.</div>
        <% end %>
      </div>
    </div>
  </div>
</div>